DROP TABLE BASEPART;
CREATE TABLE BASEPART
(
ID int,
LDRAW_REF varchar(25),
LDRAW_DESCRIPTION varchar(250),
LDRAW_CATEGORY varchar(25),
LDRAW_SIZE int,
OFFSET_X float,
OFFSET_Y float,
OFFSET_Z float,
IS_SUB_PART varchar(5),
IS_STICKER varchar(5),
IS_LARGE_MODEL varchar(5),
PART_TYPE  varchar(25),
LDRAW_PART_TYPE  varchar(25)
);
