DROP TABLE LDRAW_DETAILS;
CREATE TABLE LDRAW_DETAILS
(
	ID int,
	LDRAW_REF varchar(25),
	LDRAW_DESCRIPTION varchar(250),
	PART_TYPE varchar(25),
	LDRAW_PART_TYPE varchar(25),
	SUB_PART_COUNT int,
	DATA varchar(MAX),
	SUB_PART_LDRAW_REF_LIST varchar(MAX)
)