DELETE FROM SET_DETAILS;

INSERT INTO SET_DETAILS
(ID,REF,DESCRIPTION,TYPE,THEME,SUB_THEME,YEAR,PART_COUNT,SUBSET_COUNT,MODEL_COUNT,MINIFIG_COUNT,STATUS,ASSIGNED_TO)
VALUES
(1,'7327-1','Scorpion Pyramid','OFFICIAL','Pharaoh’s Quest','',2001,792,1,3,4,'IN_PROGRESS','LODGEANT');
